//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moj.PDO.UI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moj.PDO.UI.App_GlobalResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין קודם ערך בשדה תאריך פעילות.
        /// </summary>
        internal static string ActivityDateIsNull {
            get {
                return ResourceManager.GetString("ActivityDateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תורנות לא יכולה להתפרש על יותר מ24 שעות.
        /// </summary>
        internal static string ActivityTotalTimeOver24 {
            get {
                return ResourceManager.GetString("ActivityTotalTimeOver24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סנגור לא קיים במערכת, האם ברצונך ליצור סנגור חדש ?.
        /// </summary>
        internal static string AdvocateNotExist {
            get {
                return ResourceManager.GetString("AdvocateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שים לב, בכל הפניות שנבחרו ישתנה הפונה. האם ברצונך להמשיך?.
        /// </summary>
        internal static string AllSelectedProcessesApplicantWillChange {
            get {
                return ResourceManager.GetString("AllSelectedProcessesApplicantWillChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כבר קיים סנגור אשר הסכים להקפצה.
        /// </summary>
        internal static string AlreadyExistAdvocateAgreedToNominationCallResult {
            get {
                return ResourceManager.GetString("AlreadyExistAdvocateAgreedToNominationCallResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסנגור כבר נבחר.
        /// </summary>
        internal static string AlreadySelectedAdvocateContact {
            get {
                return ResourceManager.GetString("AlreadySelectedAdvocateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכמות והכמות משנים קודמות אינה יכולה להיות קטנה מהניצול.
        /// </summary>
        internal static string AmountAndAmountFromPreviousLessThanUsed {
            get {
                return ResourceManager.GetString("AmountAndAmountFromPreviousLessThanUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכמות אינה יכולה להיות קטנה מהניצול.
        /// </summary>
        internal static string AmountLessThanUsed {
            get {
                return ResourceManager.GetString("AmountLessThanUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שים לב, הפונה {0}  יצורף ל {1} האם אתה בטוח ?.
        /// </summary>
        internal static string ApplicantsWillJoin {
            get {
                return ResourceManager.GetString("ApplicantsWillJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שירות משרד הפנים אינו זמין.
        /// </summary>
        internal static string AvivServiceUnavailable {
            get {
                return ResourceManager.GetString("AvivServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר חפ אינו תקין.
        /// </summary>
        internal static string BusinessEntityNumberNotValid {
            get {
                return ResourceManager.GetString("BusinessEntityNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר ח.פ./זהות זהה בשתי צורות העסקה של הסנגור..
        /// </summary>
        internal static string BussinessNumberIsExist {
            get {
                return ResourceManager.GetString("BussinessNumberIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות להפחית את הכמות (אין יתרה לקיזוז).
        /// </summary>
        internal static string CanBeChangedAmountOnlyIfThereAreRemainderForReduction {
            get {
                return ResourceManager.GetString("CanBeChangedAmountOnlyIfThereAreRemainderForReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הטופס נקלט בהצלחה.
        /// </summary>
        internal static string CandidateFormAccepted {
            get {
                return ResourceManager.GetString("CandidateFormAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחוזה הסטורי אין אפשרות להוסיף לכמות.
        /// </summary>
        internal static string CanOnlyLessenAmount {
            get {
                return ResourceManager.GetString("CanOnlyLessenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לסנגור שאינו מוגדר במחוז אין אפשרות להוסיף כתובת משרד במחוז.
        /// </summary>
        internal static string CantAddAddressInDistrict {
            get {
                return ResourceManager.GetString("CantAddAddressInDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות להוסיף חוזה לסנגור שאינו פעיל במחוז.
        /// </summary>
        internal static string CantAddContract {
            get {
                return ResourceManager.GetString("CantAddContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לבחור אותו משרד כשכיר ועצמאי לאותו סנגור.
        /// </summary>
        internal static string CantChooseSameBussinessEntity {
            get {
                return ResourceManager.GetString("CantChooseSameBussinessEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לסיים את ההעסקה של העצמאי במשרד אשר קיימים בו שכירים.
        /// </summary>
        internal static string CantCloseEmploymentIfHasActiveEmployee {
            get {
                return ResourceManager.GetString("CantCloseEmploymentIfHasActiveEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לסיים את ההעסקה האחרונה של הסנגור במחוז.
        /// </summary>
        internal static string CantCloseEmploymentIfIsLast {
            get {
                return ResourceManager.GetString("CantCloseEmploymentIfIsLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שרות משרד הפנים אינו זמין, לא ניתן לקלוט סנגור שלא אומת במשרד הפנים.
        /// </summary>
        internal static string CantCreateAdvocateAvivIsNotActive {
            get {
                return ResourceManager.GetString("CantCreateAdvocateAvivIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לקלוט סנגור שאינו  קיים במשרד הפנים.
        /// </summary>
        internal static string CantCreateAdvocateIsNotExistInAviv {
            get {
                return ResourceManager.GetString("CantCreateAdvocateIsNotExistInAviv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לקלוט סנגור שאינו פעיל בלשכת עורכי הדין.
        /// </summary>
        internal static string CantCreateAdvocateIsNotExistInLicensedLawyers {
            get {
                return ResourceManager.GetString("CantCreateAdvocateIsNotExistInLicensedLawyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות למחוק חוזה אשר נוצל.
        /// </summary>
        internal static string CantDeleteContract {
            get {
                return ResourceManager.GetString("CantDeleteContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לערוך את המסמך.
        /// </summary>
        internal static string CantEditTheDocument {
            get {
                return ResourceManager.GetString("CantEditTheDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לשנות את מספר השכירים למספר הקטן ממספר השכירים הקיימים במשרד.
        /// </summary>
        internal static string CantLessenCountOfEmployee {
            get {
                return ResourceManager.GetString("CantLessenCountOfEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לבטל את האישור לשכירים נוספים מאחר וכבר נוספו השכירים.
        /// </summary>
        internal static string CantUndoTheApproval {
            get {
                return ResourceManager.GetString("CantUndoTheApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לצפות במסמך.
        /// </summary>
        internal static string CantViewTheDocument {
            get {
                return ResourceManager.GetString("CantViewTheDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רמת לוג שונתה בהצלחה.
        /// </summary>
        internal static string ChangeLogLevelSuccess {
            get {
                return ResourceManager.GetString("ChangeLogLevelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שינוי רמת לוג.
        /// </summary>
        internal static string ChangeLogLevelTitle {
            get {
                return ResourceManager.GetString("ChangeLogLevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המסמך ימחק מכל המקומות אליהם הוא מקושר. האם ברצונך להמשיך?.
        /// </summary>
        internal static string ConfirmDoumentDelete {
            get {
                return ResourceManager.GetString("ConfirmDoumentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המסמך ייפצל. האם ברצונך להמשיך ?.
        /// </summary>
        internal static string ConfirmSplit {
            get {
                return ResourceManager.GetString("ConfirmSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המיקום מקושר לפניה – קישור חדש יחליף את הקישור הנוכחי. האם להמשיך ?.
        /// </summary>
        internal static string ContactedToProcess {
            get {
                return ResourceManager.GetString("ContactedToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא לשמור את הנתונים.
        /// </summary>
        internal static string DataNotSaved {
            get {
                return ResourceManager.GetString("DataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התאריכים חופפים תאריכים של מיקום נוכחי.
        /// </summary>
        internal static string DatesOverlap {
            get {
                return ResourceManager.GetString("DatesOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם אתה בטוח שברצונך למחוק את טבלת הלוגים?.
        /// </summary>
        internal static string DeleteLogs {
            get {
                return ResourceManager.GetString("DeleteLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת הלוגים נמחקה בהצלחה!.
        /// </summary>
        internal static string DeleteLogsCompleted {
            get {
                return ResourceManager.GetString("DeleteLogsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיקת לוגים.
        /// </summary>
        internal static string DeleteLogsTitle {
            get {
                return ResourceManager.GetString("DeleteLogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היישובים שנבחרו קיימים כבר במערכת.
        /// </summary>
        internal static string DistanceCalculationIsExist {
            get {
                return ResourceManager.GetString("DistanceCalculationIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המסמך מיועד לצפייה בלבד וכל שינוי שייעשה בו לא יישמר..
        /// </summary>
        internal static string DocumentView {
            get {
                return ResourceManager.GetString("DocumentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין תעריף לתאריך תחילת החוזה, אין אפשרות לשמור את החוזה.
        /// </summary>
        internal static string DoesNoRate {
            get {
                return ResourceManager.GetString("DoesNoRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גרור את הקובץ לכאן.
        /// </summary>
        internal static string DragFile {
            get {
                return ResourceManager.GetString("DragFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צורת העסקה שונתה ותשונה גם במינויים הקשורים לחוזה, האם ברצונך להמשיך?.
        /// </summary>
        internal static string EmploymentTypeChange {
            get {
                return ResourceManager.GetString("EmploymentTypeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישות קיימת.
        /// </summary>
        internal static string EntityTypeAllreadyExist {
            get {
                return ResourceManager.GetString("EntityTypeAllreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישות לא נתמכת.
        /// </summary>
        internal static string EntityTypeNotSupported {
            get {
                return ResourceManager.GetString("EntityTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בכדי לפתוח לשונית נוספת נדרש לסגור את אחת הלשוניות הקימות.
        /// </summary>
        internal static string Err15 {
            get {
                return ResourceManager.GetString("Err15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לשנות את הסנגור בתורנות; קיימות בקשות שכ&quot;ט פעילות {0}.
        /// </summary>
        internal static string ErrActiveFeeRequestChangeAdvocate {
            get {
                return ResourceManager.GetString("ErrActiveFeeRequestChangeAdvocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לשנות את צורת ההעסקה של ההסנגור קיימות בקשות שכ&quot;ט פעילות {0}.
        /// </summary>
        internal static string ErrActiveFeeRequestChangeEmploymentType {
            get {
                return ResourceManager.GetString("ErrActiveFeeRequestChangeEmploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביצוע – &quot;משעה&quot; חייב להיות קטן מ &quot;עד שעה&quot;.
        /// </summary>
        internal static string ErrActualFromTimeGreatherThanToTime {
            get {
                return ResourceManager.GetString("ErrActualFromTimeGreatherThanToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה בהוספת המסמך.
        /// </summary>
        internal static string ErrAddDocument {
            get {
                return ResourceManager.GetString("ErrAddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות להקפיץ סנגור כאשר נבחר &quot;לא הוקפץ סנגור&quot;, יש לבטל את &quot;לא הוקפץ סנגור&quot; ולאחר מכן להקפיץ את הסנגור..
        /// </summary>
        internal static string ErrAgreedCallWithIsNoNominationConsultation {
            get {
                return ResourceManager.GetString("ErrAgreedCallWithIsNoNominationConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להוסיף רכיב - אנא הזן את כל השדות הנדרשים.
        /// </summary>
        internal static string ErrCantAddLnk {
            get {
                return ResourceManager.GetString("ErrCantAddLnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לשנות את צורת ההעסקה כאשר יש ניצול - שיבוצים הקשורים לחוזה.
        /// </summary>
        internal static string ErrChangeEmploymentTypeContractReadingUsedGreatherThanZero {
            get {
                return ResourceManager.GetString("ErrChangeEmploymentTypeContractReadingUsedGreatherThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} חייב להיות גדול או שווה ל {1}.
        /// </summary>
        internal static string ErrCheckChronologicalTime {
            get {
                return ResourceManager.GetString("ErrCheckChronologicalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימת בקשת שכ&quot;ט לסנגור בפניה, אין אפשרות לשנות לסוג המינוי המבוקש, כיון שסוג המינוי החדש אינו תואם את סוג השכ&quot;ט הקיים.
        /// </summary>
        internal static string ErrCheckNominationTypeFeeRequestCompatibility {
            get {
                return ResourceManager.GetString("ErrCheckNominationTypeFeeRequestCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אפשרות גרירת מסמכים אינה נתמכת בגרסת דוקומנטום המותקנת במחשב. על מנת לתקן את הבעיה יש לפנות למרכז השרות..
        /// </summary>
        internal static string ErrDCCVersion {
            get {
                return ResourceManager.GetString("ErrDCCVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ההפרש בין שעת סיום ביקור לשעת הקפצה אינו יכול להיות גדול או שווה ל24 שעות.
        /// </summary>
        internal static string ErrDifferenceBetweenDatesOver24Hours {
            get {
                return ResourceManager.GetString("ErrDifferenceBetweenDatesOver24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המסמך כבר מקושר לפריט.
        /// </summary>
        internal static string ErrDocumentAlreadyConnect {
            get {
                return ResourceManager.GetString("ErrDocumentAlreadyConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה בעדכון המסמך.
        /// </summary>
        internal static string ErrEditDocument {
            get {
                return ResourceManager.GetString("ErrEditDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לבחור קבוצת תעריף כאשר אין ערך בשדה מרחק בק&quot;מ.
        /// </summary>
        internal static string ErrEmptyDistanceSelectionIndication {
            get {
                return ResourceManager.GetString("ErrEmptyDistanceSelectionIndication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כאשר שעות הביצוע רבות יותר מהתכנון חובה להכניס סיבה לריבוי השעות.
        /// </summary>
        internal static string ErrEmptyShiftChangeTimeReason {
            get {
                return ResourceManager.GetString("ErrEmptyShiftChangeTimeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להזין תאריך דיון מסיים הליך כשהפניה במהלך בירור טלפוני.
        /// </summary>
        internal static string ErrEndHearingNominationDuringCall {
            get {
                return ResourceManager.GetString("ErrEndHearingNominationDuringCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לסיים מינוי כשהפניה במהלך בירור טלפוני.
        /// </summary>
        internal static string ErrEndNominationDuringCall {
            get {
                return ResourceManager.GetString("ErrEndNominationDuringCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך פעילות ב{0} חייב להיות זהה לתאריך פעילות בפרטי דרישה.
        /// </summary>
        internal static string ErrEqualSubmissionDetailsActivityDate {
            get {
                return ResourceManager.GetString("ErrEqualSubmissionDetailsActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לשנות את צורת ההקפצה של הסנגור, קיימות בקשות שכ&quot;ט פעילות.
        /// </summary>
        internal static string ErrExistFeeRequestWhenEmploymentTypeIsChanged {
            get {
                return ResourceManager.GetString("ErrExistFeeRequestWhenEmploymentTypeIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימות פניות עם מועמדים למינוי המקושרים לתורנות, אין אפשרות למחוק את התורנות.
        /// </summary>
        internal static string ErrExistNominationCandidateForShift {
            get {
                return ResourceManager.GetString("ErrExistNominationCandidateForShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימות פניות עם מועמדים למינוי המקושרים לתורנות, אין אפשרות לשנות את התורנות.
        /// </summary>
        internal static string ErrExistNominationCandidateForShiftAdvocateChange {
            get {
                return ResourceManager.GetString("ErrExistNominationCandidateForShiftAdvocateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימות פניות שמיוצגות בתורנות, אין אפשרות למחוק את התורנות.
        /// </summary>
        internal static string ErrExistNominationForShift {
            get {
                return ResourceManager.GetString("ErrExistNominationForShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימות פניות שמיוצגות בתורנות, אין אפשרות לשנות את התורנות.
        /// </summary>
        internal static string ErrExistNominationForShiftAdvocateChange {
            get {
                return ResourceManager.GetString("ErrExistNominationForShiftAdvocateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כבר קיים שיבוץ לסנגור במוקד ביום זה.
        /// </summary>
        internal static string ErrExistShiftInCurrentShiftConfiguration {
            get {
                return ResourceManager.GetString("ErrExistShiftInCurrentShiftConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות למחוק את התורנות; קיימות בקשות שכ&quot;ט פעילות {0}.
        /// </summary>
        internal static string ErrExistUnpaidFeeRequestsForShift {
            get {
                return ResourceManager.GetString("ErrExistUnpaidFeeRequestsForShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לבחור פונה או ליצור פונה חדש.
        /// </summary>
        internal static string ErrExitSearchPersonApplicant {
            get {
                return ResourceManager.GetString("ErrExitSearchPersonApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סעיף העבירה לא קיים.
        /// </summary>
        internal static string ErrFelonyLawClauseNotExist {
            get {
                return ResourceManager.GetString("ErrFelonyLawClauseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השדה שעות לא יכול להיות גדול מ24 שעות.
        /// </summary>
        internal static string ErrHoursGreaterThan24 {
            get {
                return ResourceManager.GetString("ErrHoursGreaterThan24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר מזהה הוא שדה חובה.
        /// </summary>
        internal static string ErrIdentificationNumberMandatory {
            get {
                return ResourceManager.GetString("ErrIdentificationNumberMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערך השדה שעות (זמן פעילות) אינו יכול להיות גדול מ-23 שעות.
        /// </summary>
        internal static string ErrInvalidHoursShiftTime {
            get {
                return ResourceManager.GetString("ErrInvalidHoursShiftTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערך השדה שעות (זמן נסיעה) אינו יכול להיות גדול מ-23 שעות.
        /// </summary>
        internal static string ErrInvalidHoursTravelingTime {
            get {
                return ResourceManager.GetString("ErrInvalidHoursTravelingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערך השדה שעות(זמן ביקור) אינו יכול להיות גדול מ-23 שעות.
        /// </summary>
        internal static string ErrInvalidHoursVisitTime {
            get {
                return ResourceManager.GetString("ErrInvalidHoursVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערך השדה דקות (זמן פעילות) אינו יכול להיות גדול מ-59 דקות.
        /// </summary>
        internal static string ErrInvalidMinutesShiftTime {
            get {
                return ResourceManager.GetString("ErrInvalidMinutesShiftTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערך השדה דקות (זמן נסיעה) אינו יכול להיות גדול מ-59 דקות.
        /// </summary>
        internal static string ErrInvalidMinutesTravelingTime {
            get {
                return ResourceManager.GetString("ErrInvalidMinutesTravelingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערך השדה דקות(זמן ביקור) אינו יכול להיות גדול מ-59 שעות.
        /// </summary>
        internal static string ErrInvalidMinutesVisitTime {
            get {
                return ResourceManager.GetString("ErrInvalidMinutesVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עבור הפונה מספר הליך זה כבר צורף לקבוצה אחרת.
        /// </summary>
        internal static string ErrIsExistExternalProcesses {
            get {
                return ResourceManager.GetString("ErrIsExistExternalProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימת פניה לפונה עם אותו מספר ההליך.
        /// </summary>
        internal static string ErrIsExistProcesses {
            get {
                return ResourceManager.GetString("ErrIsExistProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיים סנגור שהסכים להקפצה, יש למחוק את ההקפצה ולשמור את הנתונים לפני סימון השדה לא הוקפץ סנגור.
        /// </summary>
        internal static string ErrIsNoNominationConsultationWithAgreedCall {
            get {
                return ResourceManager.GetString("ErrIsNoNominationConsultationWithAgreedCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השדה דקות לא יכול להיות גדול מ59 דקות.
        /// </summary>
        internal static string ErrMinutesGreaterThan59 {
            get {
                return ResourceManager.GetString("ErrMinutesGreaterThan59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חובה להוסיף לפחות פניה אחת לרשימת ההליכים המצורפים.
        /// </summary>
        internal static string ErrMustToJoinProcessToJoinedProcess {
            get {
                return ResourceManager.GetString("ErrMustToJoinProcessToJoinedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שדה &quot;עד שעה&quot; לא יכול להיות לפני שדה &quot;משעה&quot; בזמן.
        /// </summary>
        internal static string ErrNegativeTimesDiff {
            get {
                return ResourceManager.GetString("ErrNegativeTimesDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to למקום {0} – {1} לא הוזן ישוב, ולכן לא ניתן לחשב מרחקים עבורו. יש לפנות למנהל מערכת..
        /// </summary>
        internal static string ErrNoCity {
            get {
                return ResourceManager.GetString("ErrNoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג המינוי של הסנגור בפניה אינו מאפשר בקשת שכר טירחה. יש לפנות למנהל מערכת..
        /// </summary>
        internal static string ErrNominationTypeNotAllowedFeeRequest {
            get {
                return ResourceManager.GetString("ErrNominationTypeNotAllowedFeeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נבחרה פניה.
        /// </summary>
        internal static string ErrNoProcessSelected {
            get {
                return ResourceManager.GetString("ErrNoProcessSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין התאמה בין צורת ההעסקה של הסנגור לצורת ההעסקה שעל המינוי. יש לפנות למנהל מערכת..
        /// </summary>
        internal static string ErrNoSameEmploymentTypes {
            get {
                return ResourceManager.GetString("ErrNoSameEmploymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לבצע שינויים נוספים בהקפצה ללא שמירה של השינויים שנעשו.
        /// </summary>
        internal static string ErrNotAdditionChangesCallsGrid {
            get {
                return ResourceManager.GetString("ErrNotAdditionChangesCallsGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  שירות משרד הפנים אינו פעיל, לא ניתן ליצור סנגור חדש, נא נסה מאוחר יותר.
        /// </summary>
        internal static string ErrNotCheckedInAviv {
            get {
                return ResourceManager.GetString("ErrNotCheckedInAviv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין לסנגור חוזה פעיל ליום זה.
        /// </summary>
        internal static string ErrNotExistActiveContract {
            get {
                return ResourceManager.GetString("ErrNotExistActiveContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לסנגור אין חוזה הקראות ליום התורנות, אין אפשרות לשבץ אותו בתורנות הקראות.
        /// </summary>
        internal static string ErrNotExistActiveReadingContract {
            get {
                return ResourceManager.GetString("ErrNotExistActiveReadingContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן ליצור סנגור שלא קיים במערכת משרד הפנים.
        /// </summary>
        internal static string ErrNotExistInAviv {
            get {
                return ResourceManager.GetString("ErrNotExistInAviv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו סנגורים המשובצים לתורנויות, לא נשלחו מכתבי שיבוץ..
        /// </summary>
        internal static string ErrNotSendAssignmentLetters {
            get {
                return ResourceManager.GetString("ErrNotSendAssignmentLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפעולה לא בוצעה, נא ודא כי המסמך אינו בשימוש משתמש אחר.
        /// </summary>
        internal static string ErrNotUpdate {
            get {
                return ResourceManager.GetString("ErrNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המרחק בין {0} לבין {1} לא קיים בטבלת מרחקים. יש לפנות למנהל מערכת..
        /// </summary>
        internal static string ErrNullDistanceValue {
            get {
                return ResourceManager.GetString("ErrNullDistanceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בסוג תורנות זה אפשר לשבץ רק סנגורים פנימים.
        /// </summary>
        internal static string ErrOnlyInternalAdvocates {
            get {
                return ResourceManager.GetString("ErrOnlyInternalAdvocates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימות פניות שנפתחו מהתורנות, אין אפשרות למחוק את התורנות.
        /// </summary>
        internal static string ErrOpenedProcessesForShift {
            get {
                return ResourceManager.GetString("ErrOpenedProcessesForShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימות פניות שנפתחו מהתורנות, אין אפשרות לשנות את התורנות.
        /// </summary>
        internal static string ErrOpenedProcessesForShiftAdvocateChange {
            get {
                return ResourceManager.GetString("ErrOpenedProcessesForShiftAdvocateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה, אנא פנה למנהל המערכת.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא עבור על כל השדות בטופס ותקן את השגויים..
        /// </summary>
        internal static string ErrorsMessageRemark {
            get {
                return ResourceManager.GetString("ErrorsMessageRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ההליך המשפטי הסתיים חובה לקשר לתיק סנגוריה.
        /// </summary>
        internal static string ErrPdoFileTab {
            get {
                return ResourceManager.GetString("ErrPdoFileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תכנון – &quot;משעה&quot; חייב להיות קטן מ &quot;עד שעה&quot;.
        /// </summary>
        internal static string ErrPlannedFromTimeGreatherThanToTime {
            get {
                return ResourceManager.GetString("ErrPlannedFromTimeGreatherThanToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר הליך או פ&quot;א הם שדות חובה.
        /// </summary>
        internal static string ErrPoliceIncidentNumberOrProcessNumberAreRequired {
            get {
                return ResourceManager.GetString("ErrPoliceIncidentNumberOrProcessNumberAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה בהדפסת המסמך.
        /// </summary>
        internal static string ErrPrintDocument {
            get {
                return ResourceManager.GetString("ErrPrintDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות למחוק את תאריך הסיום.
        /// </summary>
        internal static string ErrResetToDate {
            get {
                return ResourceManager.GetString("ErrResetToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המסמך שנבחר כבר מקושר לפריט.
        /// </summary>
        internal static string ErrSelectDocumentAlreadyConnect {
            get {
                return ResourceManager.GetString("ErrSelectDocumentAlreadyConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לשנות את תאריך תחילת המינוי מכיוון שהמינוי נפתח מתורנות בתאריך זה.
        /// </summary>
        internal static string ErrShiftNominationChangeFromDate {
            get {
                return ResourceManager.GetString("ErrShiftNominationChangeFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בביצוע יש למלא את שני השדות &quot;משעה&quot; ו&quot;&quot;עד שעה (או אף אחד מהם).
        /// </summary>
        internal static string ErrSingleActualTimeFieldIsEmpty {
            get {
                return ResourceManager.GetString("ErrSingleActualTimeFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה בפיצול המסמך.
        /// </summary>
        internal static string ErrSplitDocument {
            get {
                return ResourceManager.GetString("ErrSplitDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר פניה בפרטי בדיקה חייב להיות זהה למספר פניה בפרטי דרישה.
        /// </summary>
        internal static string ErrSubmissionDetailsExaminationDetailsProcessId {
            get {
                return ResourceManager.GetString("ErrSubmissionDetailsExaminationDetailsProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימים מינויים לפניה - לא ניתן לשנות את סטטוס זכאות.
        /// </summary>
        internal static string ErrThereIsActiveNominations {
            get {
                return ResourceManager.GetString("ErrThereIsActiveNominations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות להחליף תיק -  אין אפשרות להעביר את כל הפניות לתיק חדש.
        /// </summary>
        internal static string ErrTransferAllProcessesToNewPDOFile {
            get {
                return ResourceManager.GetString("ErrTransferAllProcessesToNewPDOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקום המוצא ומקום היעד שנבחרו נמצאים באותו הישוב. לא ניתן לשלם הוצאות נסיעה באותו הישוב..
        /// </summary>
        internal static string ErrZeroKmDistance {
            get {
                return ResourceManager.GetString("ErrZeroKmDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיים מיקום נוכחי, לאחר אישור יסומן שהפונה סיים את השהות במיקום והוא יצורף למיקומים קודמים.
        /// </summary>
        internal static string ExistCurrentLocation {
            get {
                return ResourceManager.GetString("ExistCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to למסמך זה כבר קיים קובץ, האם לדרוס ?.
        /// </summary>
        internal static string ExistFile {
            get {
                return ResourceManager.GetString("ExistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to למסמך זה כבר קיים קובץ, האם למחוק אותו?.
        /// </summary>
        internal static string ExistFileForMark {
            get {
                return ResourceManager.GetString("ExistFileForMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המסמכים נשלחו עם אינדקס.
        /// </summary>
        internal static string ExportIndexSuccess {
            get {
                return ResourceManager.GetString("ExportIndexSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שדה {0} חייב להיות תאריך..
        /// </summary>
        internal static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שדה {0} חייב להיות מספר..
        /// </summary>
        internal static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חפש לפי {filter-by}.
        /// </summary>
        internal static string FilterByText {
            get {
                return ResourceManager.GetString("FilterByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התאריך חופף תאריכים של מיקומים קודמים.
        /// </summary>
        internal static string FromDateOverlap {
            get {
                return ResourceManager.GetString("FromDateOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג זיהוי ומספר זיהוי זה כבר קיימים במערכת.
        /// </summary>
        internal static string IdNumberAlreadyExist {
            get {
                return ResourceManager.GetString("IdNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר תעודת זהות לא תקין.
        /// </summary>
        internal static string IdNumberIsNotValid {
            get {
                return ResourceManager.GetString("IdNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשומה אחרת פתוחה לעדכון ,הנתונים ימחקו . &lt;/br&gt;האם ברצונך להמשיך?.
        /// </summary>
        internal static string InlineNewEditMessage {
            get {
                return ResourceManager.GetString("InlineNewEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא לשמור את הרשומה שהוקלדה.
        /// </summary>
        internal static string InlineNewEditSaveMessage {
            get {
                return ResourceManager.GetString("InlineNewEditSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר תעודת זהות אינו תקין.
        /// </summary>
        internal static string InvalidAdvocateID {
            get {
                return ResourceManager.GetString("InvalidAdvocateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך הדיון קטן מתאריך הפניה.
        /// </summary>
        internal static string InvalidHearingDate {
            get {
                return ResourceManager.GetString("InvalidHearingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חובה להזין אותיות בעברית בלבד.
        /// </summary>
        internal static string InvalidHebrewPattern {
            get {
                return ResourceManager.GetString("InvalidHebrewPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תעודת זהות אינה תקינה, האם להמשיך?.
        /// </summary>
        internal static string InvalidID {
            get {
                return ResourceManager.GetString("InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תעודת זהות לא תקינה.
        /// </summary>
        internal static string InvalidIdentificationNo {
            get {
                return ResourceManager.GetString("InvalidIdentificationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חובה להזין לפחות מספר טלפון אחד.
        /// </summary>
        internal static string InvalidNoPhones {
            get {
                return ResourceManager.GetString("InvalidNoPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסימן % יכול להופיע רק פעם אחת בתחילת/בסוף ערך החיפוש.
        /// </summary>
        internal static string InvalidObjectToSearchPercent {
            get {
                return ResourceManager.GetString("InvalidObjectToSearchPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השדה לא יכול להכיל רק ספרות.
        /// </summary>
        internal static string InvalidOnlyNumbers {
            get {
                return ResourceManager.GetString("InvalidOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עילת מינוי תימחק – האם להמשיך?.
        /// </summary>
        internal static string IsDeletedNominationGround {
            get {
                return ResourceManager.GetString("IsDeletedNominationGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עילת מינוי תימחק, ותום הייצוג יוסר – האם להמשיך.
        /// </summary>
        internal static string IsDeletedNominationGroundAndEndOfRepresentation {
            get {
                return ResourceManager.GetString("IsDeletedNominationGroundAndEndOfRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עילת המינוי של הפניה תתעדכן לעילת המינוי של הפניה המקושרת האם להמשיך?.
        /// </summary>
        internal static string IsUpdateProcessNominationGround {
            get {
                return ResourceManager.GetString("IsUpdateProcessNominationGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השדה חייב להיות באורך מקסימלי של {0} תווים..
        /// </summary>
        internal static string MaxLengthMessage {
            get {
                return ResourceManager.GetString("MaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר השכירים המירבי הוא.
        /// </summary>
        internal static string MaxNumberOfEmployeesIs {
            get {
                return ResourceManager.GetString("MaxNumberOfEmployeesIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר מוטב מרכבה זהה בשתי צורות ההעסקה של הסנגור..
        /// </summary>
        internal static string MerkavaNumberIsExist {
            get {
                return ResourceManager.GetString("MerkavaNumberIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לשלוח הודעה זו ללא תוכן?.
        /// </summary>
        internal static string MissingBodyAlert {
            get {
                return ResourceManager.GetString("MissingBodyAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיים לפניה יותר ממינוי אחד פעיל.
        /// </summary>
        internal static string MoreOneActiveNominationForProcess {
            get {
                return ResourceManager.GetString("MoreOneActiveNominationForProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיווצר פניה חדשה , האם ברצונך להמשיך?.
        /// </summary>
        internal static string MsgCreateNewProcess {
            get {
                return ResourceManager.GetString("MsgCreateNewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המינויים הפתוחים לפניה יסגרו האם ברצונך להמשיך?.
        /// </summary>
        internal static string MsgEndProcessHearingDate {
            get {
                return ResourceManager.GetString("MsgEndProcessHearingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימים ערכים בשדות פרטי הזיהוי, יועתקו רק נתוני הכתובת \n.
        /// </summary>
        internal static string MsgOnlyAddressCopy {
            get {
                return ResourceManager.GetString("MsgOnlyAddressCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to במערכת כבר קיים פונה עם שם משפחה ושם פרטי זהה. האם להמשיך?.
        /// </summary>
        internal static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין תחילה את תאריך התחלת החוזה.
        /// </summary>
        internal static string NeedFillStartDateInFirst {
            get {
                return ResourceManager.GetString("NeedFillStartDateInFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נמצא הליך ללא הליך פונה, האם ברצונך להמשיך ליצור הליך לפונה?.
        /// </summary>
        internal static string NoApplicantProcess {
            get {
                return ResourceManager.GetString("NoApplicantProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נבחרו מסמכים.
        /// </summary>
        internal static string NoDocumentsChecked {
            get {
                return ResourceManager.GetString("NoDocumentsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניתן לפצל קובץ PDF בלבד.
        /// </summary>
        internal static string NoPDF {
            get {
                return ResourceManager.GetString("NoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצא הליך, האם ברצונך להמשיך ליצור הליך?.
        /// </summary>
        internal static string NoProcess {
            get {
                return ResourceManager.GetString("NoProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא לבחור רשומה.
        /// </summary>
        internal static string NoSelectRecord {
            get {
                return ResourceManager.GetString("NoSelectRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפרמטר לאיתור יכול להכיל רק ספרות ואותיות.
        /// </summary>
        internal static string ObjectToSearchIsNotValid {
            get {
                return ResourceManager.GetString("ObjectToSearchIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רק בעל הרשאה של סנגור ארצי יכול להגדיל את מספר השכירים למשרד .
        /// </summary>
        internal static string OnlyDistrictAttorneyCanAddOverMaxNumberOfEmployees {
            get {
                return ResourceManager.GetString("OnlyDistrictAttorneyCanAddOverMaxNumberOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רק בעל הרשאה של סנגור ארצי יכול לשנות את השדה אישור לשכירים נוספים..
        /// </summary>
        internal static string OnlyDistrictAttorneyCanApproveMoreEmployee {
            get {
                return ResourceManager.GetString("OnlyDistrictAttorneyCanApproveMoreEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיק סנגוריה לא קיים.
        /// </summary>
        internal static string PdoFileIdNotExist {
            get {
                return ResourceManager.GetString("PdoFileIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר תיק לא קיים.
        /// </summary>
        internal static string PDOFileNotExist {
            get {
                return ResourceManager.GetString("PDOFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו פניות קודמות לפונה לאותו מספר הליך ו/או סוג הליך, ניתן להמשיך בתהליך.
        /// </summary>
        internal static string PreviousProcessesNotExist {
            get {
                return ResourceManager.GetString("PreviousProcessesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המסמכים נשלחו להדפסה.
        /// </summary>
        internal static string PrintSent {
            get {
                return ResourceManager.GetString("PrintSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  קטגורית ההליך שונתה, כל פרטי ההליך ימחקו, האם ברצונך להמשיך?.
        /// </summary>
        internal static string ProcessCategoryChanged {
            get {
                return ResourceManager.GetString("ProcessCategoryChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פניה לא קיימת במערכת, האם ברצונך ליצור פניה חדשה ?.
        /// </summary>
        internal static string ProcessNotExist {
            get {
                return ResourceManager.GetString("ProcessNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר ההליך שונה כל פרטי ההליך ימחקו, האם ברצונך להמשיך?.
        /// </summary>
        internal static string ProcessNumberChanged {
            get {
                return ResourceManager.GetString("ProcessNumberChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר ההליך לא ידוע, תוצאות איתור פניה קודמת ימחקו, האם ברצונך להמשיך?.
        /// </summary>
        internal static string ProcessNumberUnKnownChanged {
            get {
                return ResourceManager.GetString("ProcessNumberUnKnownChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג ההליך שונה, כל פרטי ההליך ימחקו, האם ברצונך להמשיך?.
        /// </summary>
        internal static string ProcessTypeChanged {
            get {
                return ResourceManager.GetString("ProcessTypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערך {0} אינו תקין עבור {1}..
        /// </summary>
        internal static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוים לא תקינים.
        /// </summary>
        internal static string PropertyValueInvalidCharacters {
            get {
                return ResourceManager.GetString("PropertyValueInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} שדה חובה..
        /// </summary>
        internal static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הזן תאריך בין {0} ל-{1}.
        /// </summary>
        internal static string RangeOfDates {
            get {
                return ResourceManager.GetString("RangeOfDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לסמן &quot;ללא קובץ&quot; כאשר נבחר מסמך. האם להסיר את המסמך שנבחר ?.
        /// </summary>
        internal static string RemoveBrowseDocument {
            get {
                return ResourceManager.GetString("RemoveBrowseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לבחור מסמך. יש להסיר את הסימון מ&quot;ללא קובץ &quot;..
        /// </summary>
        internal static string RemoveWithoutFile {
            get {
                return ResourceManager.GetString("RemoveWithoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות שהסנגור יחליף את עצמו.
        /// </summary>
        internal static string SameAdvocatesInReplacement {
            get {
                return ResourceManager.GetString("SameAdvocatesInReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המרחק נשמר בהצלחה.
        /// </summary>
        internal static string SaveDistanceMessage {
            get {
                return ResourceManager.GetString("SaveDistanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר סוג מוסד.
        /// </summary>
        internal static string SelectPlaceType {
            get {
                return ResourceManager.GetString("SelectPlaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נשלחו מכתבי שיבוץ ל {0} סנגורים במחוז.
        /// </summary>
        internal static string SentAssignmentLettersMessage {
            get {
                return ResourceManager.GetString("SentAssignmentLettersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך איחוד הפונים התבצע בהצלחה.
        /// </summary>
        internal static string SuccessJoinApplicants {
            get {
                return ResourceManager.GetString("SuccessJoinApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השמירה בוצעה בהצלחה.
        /// </summary>
        internal static string SuccessSave {
            get {
                return ResourceManager.GetString("SuccessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פניה {0} נשמרה בהצלחה.
        /// </summary>
        internal static string SuccessSaveNewProcess {
            get {
                return ResourceManager.GetString("SuccessSaveNewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך העברת פניות בין פונים הסתיים בהצלחה.
        /// </summary>
        internal static string SuccessTransferProcessesFromApplicant {
            get {
                return ResourceManager.GetString("SuccessTransferProcessesFromApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך העברת הפניות בין ממנים הסתיים בהצלחה.
        /// </summary>
        internal static string SuccessTransferProcessesFromNominator {
            get {
                return ResourceManager.GetString("SuccessTransferProcessesFromNominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העברת הפניות בין התיקים הסתיימה בהצלחה.
        /// </summary>
        internal static string SuccessTransferProcessesFromPDOFile {
            get {
                return ResourceManager.GetString("SuccessTransferProcessesFromPDOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  העברת הפניות לתיק חדש מספר {0} הסתיימה בהצלחה.
        /// </summary>
        internal static string SuccessTransferProcessesToNewPDOFile {
            get {
                return ResourceManager.GetString("SuccessTransferProcessesToNewPDOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניתן להפחית את הכמות עד ל -{0}.
        /// </summary>
        internal static string TheLessHasToBeToAmountOfRemainderForReduction {
            get {
                return ResourceManager.GetString("TheLessHasToBeToAmountOfRemainderForReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימים מינויים פעילים עבור הפניה – בסימון &quot;תום ייצוג&quot; המינויים יסתיימו..
        /// </summary>
        internal static string ThereIsActiveNomination {
            get {
                return ResourceManager.GetString("ThereIsActiveNomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימות פניות המקושרות כפנייה נוספת או נלוות, יש לנתק את הקשר לפני הפיכת הפניה ללא זכאית..
        /// </summary>
        internal static string ThereIsAttachedProcessDisconnectTheProcess {
            get {
                return ResourceManager.GetString("ThereIsAttachedProcessDisconnectTheProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנתונים אינם תקינים.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך להמשיך?.
        /// </summary>
        internal static string Wrn13 {
            get {
                return ResourceManager.GetString("Wrn13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפניה כבר מקושרת לפניית אב. נתק את הקשר הקודם כדי לקשר לפניית אב אחרת.
        /// </summary>
        internal static string WrnAccompanyingProcessAllreadyExist {
            get {
                return ResourceManager.GetString("WrnAccompanyingProcessAllreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסנגור כבר מועמד למינוי לפניה.
        /// </summary>
        internal static string WrnAdvocateAlreadyExist {
            get {
                return ResourceManager.GetString("WrnAdvocateAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא קיימות פניות בקבוצת הצירוף, המידע של ההליכים הנוספים ימחק, האם ברצונך להמשיך?.
        /// </summary>
        internal static string WrnAllJoinedProcessesDeleted {
            get {
                return ResourceManager.GetString("WrnAllJoinedProcessesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לקשר לתיק נוכחי.
        /// </summary>
        internal static string WrnAttachedCurrentPDOFile {
            get {
                return ResourceManager.GetString("WrnAttachedCurrentPDOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיים קישור לתיק זה.
        /// </summary>
        internal static string WrnAttachedPDOFileExist {
            get {
                return ResourceManager.GetString("WrnAttachedPDOFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימים לפניה מינויים מסוג ריטיינר, ובית המשפט החדש לא מאפשר מינויים כאילו. האם ברצונך להמשיך?.
        /// </summary>
        internal static string WrnChagneCourtAffectRetainer {
            get {
                return ResourceManager.GetString("WrnChagneCourtAffectRetainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם להפוך את כתובת המרשם החדשה לכתובת למשלוח דואר?.
        /// </summary>
        internal static string WrnConvertNewAddressToMainAddress {
            get {
                return ResourceManager.GetString("WrnConvertNewAddressToMainAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך הקליטה שהוזן שונה מתאריך הקליטה של הבקשה. האם להשאיר את התאריך שהוזן?.
        /// </summary>
        internal static string WrnDifferentsReceivedDates {
            get {
                return ResourceManager.GetString("WrnDifferentsReceivedDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחרת פונה אחר, כל הנתונים שהוזנו ימחקו האם ברצונך להמשיך?.
        /// </summary>
        internal static string WrnExitSearchPersonApplicant {
            get {
                return ResourceManager.GetString("WrnExitSearchPersonApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צורת ההעסקה לסנגור של {0} המעודכנת בבקשה אינה פעילה יותר לסנגור במחוז {1}. לא ניתן יהיה לעדכן שורות שכ&quot;ט בבקשה או לאשר אותה אישור סופי..
        /// </summary>
        internal static string WrnFeeRequestEmploymentTypeNotExist {
            get {
                return ResourceManager.GetString("WrnFeeRequestEmploymentTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא מולא דיון, האם ברצונך להמשיך?.
        /// </summary>
        internal static string WrnFutureHearingEmpty {
            get {
                return ResourceManager.GetString("WrnFutureHearingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא קיים מוטב מרכב&quot;ה לצורת ההעסקה לסנגור בפניה. יש לפנות לאחראי על הנושא בסנגוריה..
        /// </summary>
        internal static string WrnHearingModuleHasNotBusinessEntityMerkava {
            get {
                return ResourceManager.GetString("WrnHearingModuleHasNotBusinessEntityMerkava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיים יותר ממוטב מרכבה אחד  לצורת ההעסקה לסנגור בבקשה.
        /// </summary>
        internal static string WrnHearingModuleHaveMoreThanOneBusinessEntityMerkava {
            get {
                return ResourceManager.GetString("WrnHearingModuleHaveMoreThanOneBusinessEntityMerkava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימים ערכים בשדות פרטי הזיהוי \n.
        /// </summary>
        internal static string WrnIdentificationDetailsValues {
            get {
                return ResourceManager.GetString("WrnIdentificationDetailsValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות להוסיף סנגור נוסף כאשר סטטוס המינוי הוא &quot;מינוי&quot;.
        /// </summary>
        internal static string WrnInvalidAddAdvocate {
            get {
                return ResourceManager.GetString("WrnInvalidAddAdvocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שימו לב, המחליף שנבחר אינו מורשה להחליף את הסנגור.
        /// </summary>
        internal static string WrnIsNotReplacementAuthorized {
            get {
                return ResourceManager.GetString("WrnIsNotReplacementAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין פרמטר לחיפוש.
        /// </summary>
        internal static string WrnMissingSearchValue {
            get {
                return ResourceManager.GetString("WrnMissingSearchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יתבצע איתור חדש, האם ברצונך להמשיך?.
        /// </summary>
        internal static string WrnNewSearch {
            get {
                return ResourceManager.GetString("WrnNewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות למנות כאשר יש יותר מסנגור אחד.
        /// </summary>
        internal static string WrnNominationMoreThanOneAdvocate {
            get {
                return ResourceManager.GetString("WrnNominationMoreThanOneAdvocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בשינוי הממנה לא ישמרו נתוני המינוי ששונו; האם ברצונך להמשיך?.
        /// </summary>
        internal static string WrnNominatorChanged {
            get {
                return ResourceManager.GetString("WrnNominatorChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקשר בין הפניות ימחק – יש לבחור עילת מינוי חדשה.
        /// </summary>
        internal static string WrnProcessConnectionDeletedChooseNewNominationGround {
            get {
                return ResourceManager.GetString("WrnProcessConnectionDeletedChooseNewNominationGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בית המשפט החדש זהה לבית המשפט הקודם..
        /// </summary>
        internal static string WrnProcessCourtsAreSame {
            get {
                return ResourceManager.GetString("WrnProcessCourtsAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין לפניה הסטוריית שינויים בשדה בית משפט.
        /// </summary>
        internal static string WrnProcessHasNoCourtChangesHistory {
            get {
                return ResourceManager.GetString("WrnProcessHasNoCourtChangesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין לפניה הסטוריית שינויים במספר הליך.
        /// </summary>
        internal static string WrnProcessHasNoProcessNumberChangesHistory {
            get {
                return ResourceManager.GetString("WrnProcessHasNoProcessNumberChangesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין לפניה הסטוריית שינויים בסטטוס הפניה.
        /// </summary>
        internal static string WrnProcessHasNoStatusChangesHistory {
            get {
                return ResourceManager.GetString("WrnProcessHasNoStatusChangesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נתוני מספר ההליך החדשים זהים לנתונים הקיימים..
        /// </summary>
        internal static string WrnProcessNumbersAreSame {
            get {
                return ResourceManager.GetString("WrnProcessNumbersAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נבחרה קידומת למספר הליך האם ברצונך להמשיך?.
        /// </summary>
        internal static string WrnProcessPrefixEmpty {
            get {
                return ResourceManager.GetString("WrnProcessPrefixEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימת פניה מקושרת זהה.
        /// </summary>
        internal static string WrnProcessSelected {
            get {
                return ResourceManager.GetString("WrnProcessSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שים לב, הנתונים במסך פרטי גורם בתיק לא נשמרו, בהמשך שמירה הם יאבדו.
        /// </summary>
        internal static string WrnSaveParty {
            get {
                return ResourceManager.GetString("WrnSaveParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא בוצע איתור הליך אב להליך נלוה.
        /// </summary>
        internal static string WrnSearchParentProcess {
            get {
                return ResourceManager.GetString("WrnSearchParentProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לבצע איתור פניה קודמת.
        /// </summary>
        internal static string WrnSearchPreviousProcess {
            get {
                return ResourceManager.GetString("WrnSearchPreviousProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיימות לפניה שבחרת פניות קשורות יש להעביר גם אותן, האם ברצונך לבצע את ההעברה?.
        /// </summary>
        internal static string WrnSelectedProcessHaveAttachedProcess {
            get {
                return ResourceManager.GetString("WrnSelectedProcessHaveAttachedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא קיים מוטב מרכב&quot;ה לצורת ההעסקה לסנגור בבקשה. יש לפנות לאחראי על הנושא בסנגוריה..
        /// </summary>
        internal static string WrnShiftModuleHasNotBusinessEntityMerkava {
            get {
                return ResourceManager.GetString("WrnShiftModuleHasNotBusinessEntityMerkava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כל הפניות יועברו מתיק  {0}. התיק יסגר, כל הפניות, התרשומות, התזכורות והמסמכים יועברו  לתיק היעד  {1} - האם  ברצונך להמשיך?.
        /// </summary>
        internal static string WrnTransferAllPDOFileProcesses {
            get {
                return ResourceManager.GetString("WrnTransferAllPDOFileProcesses", resourceCulture);
            }
        }
    }
}
